@startuml
title: Notification
footer: Common Gateway Plugin | Commongateway | Xxllnctoktbbundle 
header: Schema

class Notification {
  + case_number: integer
  + entity_id: string
  + case_uuid: string
  + changes: array
  + entity_type: string
  + event_name: string
  + description: string
}
@enduml
